<?php
$texte = array ("SITE_commentaire" 	=> array("Site et Jeu goupillés par Ode & LeCh@p'$ (Pour plus de renseignements, disponibles par Téléphone Portatif, Facebook, Tatoo, Minitel, Télégramme ou Pigeon voyageur)", 
											"Made in Peigneurs Street", 
											"Fabriqué main, mais quel pied!!!!  ;-)"), 
		"LIEN_presentation"			=> array("Présentation", "Accueil", "Bienvenue"),
		"LIEN_title_presentation"	=> array("Présentation du jeu", "Si tu connais le site tu t'en fou!", "Généralités, bla-bla-bla..."),
		"LIEN_indice"				=> array("Indice"),
		"LIEN_title_indice"			=> array("Indices", "La partie la plus interessante du site ;-)", "Pour réfléchir!", "A lire attentivement"),
		"LIEN_reponse"				=> array("Réponse"),
		"LIEN_title_reponse"		=> array("Réponse", "L'instant de vérité", "Tente ta chance?!"),
		"LIEN_administration"		=> array("Administration", "Admin", "?"),
		"LIEN_title_administration"	=> array("Administration", "Pour les initiés", "Accès restreints, très restreints!!!", "Inutile..."), 
		"BOUTON_valider"			=> array("Valider", "Enregistrer", "Let's GO", "Sauver", "Clic Me I'm Famous"), 
		"INSCRIPTION"				=> array("S'incrire par mail pour être prévenu de l'évolution du jeu, et de son départ!!!", 
											"Saisir un email valide afin de pouvoir participer à ce jeu", 
											"Fais-toi connaitre en renseignant ton mail"), 
		"MAIL_etat0"				=> array("Salut #NOM, content que tu participes à ce jeu, à très bientôt ;-)", 
											"Merci #NOM, c'est un honneur que tu participes à cette aventure", 
											"#NOM, un joueur à surveiller, à coup sur!!!!"), 
		"MAIL_etat1"				=> array("Je te reconnais bien là #NOM, tu as déjà inscrit ce mail!!!", 
											"Sacré #NOM, je te reconnais bien là à tenter de te réinscrire", 
											"#NOM, tu est déjà inscrit, rassures-toi ;-)"),
		"MAIL_etat2"				=> array("Bienvenue, ton mail #NOM est transmis aux administrateurs pour validation, tu recevras une confirmation dans les prochains jours.", 
											"Welcome, j'enregistre précieusement ton mail #NOM, tu seras averti de sa validation.", 
											"Bien joué, je valide rapidement ce mail #NOM afin que tu puisses jouer rapidement."),
		"MAIL_etat2_repeat"			=> array("Bonjour, le mail #NOM nous est déjà parvenu, il est en attente de validation...", 
											"#NOM, ce mail est déjà renseigné, mais il est en attente de validation.", 
											"Ton mail (#NOM) est déjà connu, il sera bientôt valider, patience..."),
		"MAIL_etat3"				=> array("Salut, le mail #NOM à l'interdiction formelle de participer à ce jeu...dommage...", 
											"Le mail #NOM est rejeté par le site...désolé.", 
											"#NOM fait partie des mails interdits, il y a forcément une raison.", 
											"J'ai beau vérifié, le mail #NOM est interdit sur ce site."), 
		"MAIL_etat01_visite"		=> array("Salut #NOM, ça va aujourd'hui ?!", 
											"Pas la peine de te cacher je sais que c'est toi #NOM ;-)", 
											"#NOM, nous sommes, content que tu reviennes.",
											"Un grand bonjour #NOM, bonne chance à toi."),
		"MAIL_etat2_visite"			=> array("Bonjour, cet mail #NOM est en attente de validation...",
											"Un peu de patience, #NOM est en attente de validation..."),
		"MAIL_revocation"			=> array("Pour révoquer ce mail clique ici.",
											"Mare ce ce mail?! clique ici.", 
											"Pour oublier ce mail clique-ici",
											"Pour saisir un autre mail, clique-ici"),
		"INDICE"					=> array("Compte à rebours du prochain indice (ce dernier sera visible #NOM)", 
											"Ci-dessous le temps d'attente avant le prochain indice, ce dernier sera visible #NOM"),
		"REPONSE_saisie"			=> array("Saisie de la réponse", 
											"Pour répondre les deux champs sont à remplir, pour gagner, le second doit être correct ;-)", 
											"Formulaire de saisie de la réponse, ou plutôt de la tentative de réponse ;-)", 
											"Stressé avant de répondre?"), 
		"REPONSE_ok"				=> array("Au plus vite, appel Aude (0648176677) ou Romain(0676984314)...au fait, quel est ton vin préféré?"), 
		"REPONSE_ko"				=> array("Je crois qu'ça va pas être possible...", "Ah non c'est pas pour aujourd'hui..."), 
		"REPONSE_interval"			=> array("Attention #NOM!!! L'intervalle entre deux propositions n'est pas respecté.", 
											"Toujours autant préssé #NOM, respecte d'abord l'intervalle de réponse ", 
											"Patience, tu ne peux pas répondre autant de fois que tu veux..."), 
		"REPONSE_etat2"				=> array("Le mail #NOM n'est pas encore autorisé..patience."), 
		"REPONSE_etat3"				=> array("Le mail #NOM est interdit de participation...dommage."), 
		"REPONSE_etat0_verif"		=> array("Hey #NOM, content que tu participes à ce jeu."), 
		"REPONSE_etat1_verif"		=> array("Tiens!! Salut #NOM, ça va aujourd'hui?!", 
											"#NOM, Quel honneur!", 
											"Salut #NOM, tu es venu faire ton quinté?"), 
		"REPONSE_wait"				=> array("C'est pourquoi, la réponse ne sera pas vérifiée.", 
											"En attendant tu comprends que ta réponse ne soit pas vérifiée..."), 
		"REPONSE_liste"				=> array("Voici les réponses proposées : ", "Voici les prénoms proposés :", "Voici les propositions déjà testées : "), 
		"ADMIN_accueil"				=> array("Evidemment un Code d'accès est nécessaire pour accéder à partie administration : "), 
		"INDICE_liste"				=> array("Voici la liste des indices à disposition : ", "Les indices : "),
		"GAME_ENDED"				=> array("Tu arrive trop tard, la bonne réponse a déjà été trouvée", "Je sens ta déception...mais nous avons déjà un vainqueur",
											"oh NON, le prénom viens juste d'être donné", "C'est trop tard, j'ai déjà mon vainqueur")		
);?>